
void main() 
{
    printf("██╗  ██╗███╗   ██╗███████╗██╗\n");
    printf("╚██╗██╔╝████╗  ██║██╔════╝██║\n");
    printf(" ╚███╔╝ ██╔██╗ ██║█████╗  ██║\n");
    printf(" ██╔██╗ ██║╚██╗██║██╔══╝  ██║\n");
    printf("██╔╝ ██╗██║ ╚████║███████╗███████╗\n");
    printf("╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝\n");
    /* Login */
    // Username
    char userName[30];

    // Ask the user to input some text
     printf("Enter your username: \n");

     // Get and save the text
     scanf("%s", userName);

     // Output the text
     printf("Hello %s welcome to the Xnel. \n", userName);

     // Password
     int MypassWord;

     // Ask the user to type a password
      printf("Type a password and press enter: \n"); 

      // Get and save the password the user types
      scanf("%d", &MypassWord);

      // Print the number the user typed
      printf("Your password is: %d\n\r", MypassWord);

     // End tag
     
    while (1); // Infinte loop
}   
/*
( C ) The xnel software
DO NOT EDIT THIS FILE
website: in link
*/